### ISSUE TITLE
signal handler override

### ISSUE THREAD

**Issue by daroczig** [josiahcarlson/jobs#3]
I've seen some silent errors recently and after some shotgun debugging I ended up with the below minimal example:

```python
import os
import signal
import threading
import time
#import jobs
def selfkill():
  time.sleep(5)
  os.kill(os.getpid(), signal.SIGTERM)
x = threading.Thread(target=selfkill)
x.start()
time.sleep(10)
print('OK')    
```

This will of course stop after 5 seconds with exit code ~143 or so, *but* if commenting out `import jobs`, it will exit without an error and exic code 0 :thinking_face:

I suspect this is happening because of https://github.com/josiahcarlson/jobs/blob/master/jobs.py#L323

I am not quite sure about the background and why we need to override the signal handler -- can you please help me understand what I am doing wrong or some pointers on how to fix this? In short, I want the above job (after uncommenting `import jobs`) to fail due to the `SIGTERM`.

**Comment by josiahcarlson** [comment]
The signal handler exists in order to clean up any resource managers that have job locks in other threads.

Assuming this is at System1, you are using `jobs` in combination with my other project/library `rpqueue`, which uses sub-processes and sub-threads in order to do more than 1 thing at a time. I/we had explicitly added the signal handler override to handle concurrently open jobs, unlocking inputs and outputs on signal / crash / shutdown.

The right answer is bubbling up the error status from the signal handler, and letting the caller decide how to handle the non-success error codes. I'll have a patch for that later tonight.

**Comment by josiahcarlson** [comment]
Okay, 0.27.0 was just released and tagged. It includes proper pass through of signals -> exit codes, per signal -> exit code spec. It also includes timeouts for job outputs, if you want/need them.

Thank you for the question that turned into a bug report and fix.

**Comment by josiahcarlson** [comment]
And here is the relevant changelist:
https://github.com/josiahcarlson/jobs/commit/d8bb54b7871cdc6ce3ef2dd7f771d4e4653f858d

**Comment by daroczig** [comment]
Thanks a lot, @josiahcarlson :bowing_man:
